-- 1. Khởi tạo Database
CREATE DATABASE IF NOT EXISTS truonghoc;
USE truonghoc;


CREATE TABLE KHOA
(
  MAKHOA VARCHAR (30) NOT NULL ,
  TENKHOA VARCHAR(20) NOT NULL,
  NGTLAP DATE,
  TRGKHOA VARCHAR(30) NOT NULL,
  PRIMARY KEY (MAKHOA)
);


 CREATE TABLE GIAOVIEN
 (
   MAGV VARCHAR(20) NOT NULL,
   HOTEN VARCHAR(100) NOT NULL,
   HOCVI INT NOT NULL,
   HOCHAM VARCHAR(4) NOT NULL,
   GIOITINH VARCHAR(7),
   HESO INT ,
   PRIMARY KEY (MAGV)
);

 INSERT INTO truonghoc.KHOA (MAKHOA, TENKHOA, NGTLAP, TRGKHOA)
 VALUES
   ('0132151006', 'cong nghe ky thuat', 2002-04-13, 'OH LY SHIN'),
   ('0133807800', 'Y HOC CO TRUYEN', 2003-03-12, 'BAC YU BIN'),
   ('0132575655', 'Y DUOC', 2004-05-28, 'CHU MAO'),
   ('013299044X', 'QUAN TRIN KHACH SAN',2000-01-30, 'NI HAO MI');

 INSERT INTO truonghoc.GIAOVIEN (MAGV, HONTEN, HOCVI, HOCHAM, GIOITINH, HESO)
 VALUES
   ('0132', 'VO VAN L', 'THAC SI', 'PHO GIAO SU','NU',7),
   ('0133', 'NGO XUAN S', 'TIEN SY', 'GIAO SU','NAM',5),
   ('0132', 'TRAN VAN H', 'TIEN SI', 'GIAO SU','NAM',4),
   ('0152', 'QUAN XUAN Q','TIEN SI', 'GIAO SU','NU',3);


 SELECT * FROM truonghoc.KHOA;
 SELECT * FROM truonghoc.GIAOVIEN;
